version: '3'
services:
  ec2-dashboard:
    image: jafferraza123/dasboard
    container_name: aws-ec2-dashboard-v1
    ports:
      - "5006:5000"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ap-south-1
    volumes:
      - ./app:/app
